// Generated by scripts/extract-animals.py from the Farm friends deck. Do not edit by hand.
export type Eye = { x: number; y: number; w: number; h: number; delay: number };
export type Layer = { kind: string; origin: [number, number] | null; svg: string; eyes?: Eye[] };
export type AnimalArt = { defs: string; layers: Layer[] };
export const ANIMAL_ART: Record<string, AnimalArt> = {
 "cow": {
  "defs": "<filter id=\"cow-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"cow-s\"><feGaussianBlur stdDeviation=\"7\"/></filter><clipPath id=\"cow-cb\"><ellipse cx=\"270\" cy=\"300\" rx=\"175\" ry=\"105\"/></clipPath><clipPath id=\"cow-ch\"><ellipse cx=\"460\" cy=\"200\" rx=\"95\" ry=\"88\"/></clipPath>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"285\" cy=\"470\" rx=\"200\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#cow-s)\" style=\"transform-origin:285px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     108.0,
     262.0
    ],
    "svg": "<g filter=\"url(#cow-w)\"><path d=\"M108 262 Q60 300 78 385\" fill=\"none\" stroke=\"#6f5d55\" style=\"stroke-width:9\"/><ellipse cx=\"78\" cy=\"398\" rx=\"15\" ry=\"22\" fill=\"#6f5d55\" /></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#cow-w)\"><rect x=\"165\" y=\"355\" width=\"46\" height=\"110\" rx=\"23\" fill=\"#eadcc3\" stroke=\"#cdb892\" /><rect x=\"163\" y=\"441\" width=\"50\" height=\"24\" rx=\"10\" fill=\"#6f5d55\" /><rect x=\"345\" y=\"355\" width=\"46\" height=\"110\" rx=\"23\" fill=\"#eadcc3\" stroke=\"#cdb892\" /><rect x=\"343\" y=\"441\" width=\"50\" height=\"24\" rx=\"10\" fill=\"#6f5d55\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#cow-w)\"><ellipse cx=\"305\" cy=\"395\" rx=\"36\" ry=\"24\" fill=\"#f6b4b0\" stroke=\"#d98a88\" /><ellipse cx=\"270\" cy=\"300\" rx=\"175\" ry=\"105\" fill=\"#fbf3e6\" stroke=\"#cdb892\" /><g clip-path=\"url(#cow-cb)\"><path d=\"M150 190 Q230 200 225 260 Q215 320 150 310 Q90 300 100 240Z\" fill=\"#6f5d55\" /><path d=\"M300 330 Q360 300 395 345 Q410 420 340 415 Q285 400 300 330Z\" fill=\"#6f5d55\" /><ellipse cx=\"320\" cy=\"215\" rx=\"34\" ry=\"22\" fill=\"#6f5d55\" /></g></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#cow-w)\"><rect x=\"118\" y=\"365\" width=\"48\" height=\"102\" rx=\"24\" fill=\"#fbf3e6\" stroke=\"#cdb892\" /><rect x=\"116\" y=\"443\" width=\"52\" height=\"24\" rx=\"10\" fill=\"#6f5d55\" /><rect x=\"385\" y=\"365\" width=\"48\" height=\"102\" rx=\"24\" fill=\"#fbf3e6\" stroke=\"#cdb892\" /><rect x=\"383\" y=\"443\" width=\"52\" height=\"24\" rx=\"10\" fill=\"#6f5d55\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     440.0,
     270.0
    ],
    "svg": "<g filter=\"url(#cow-w)\"><path d=\"M412 135 Q392 95 408 80 Q428 100 436 128Z\" fill=\"#efdfb5\" stroke=\"#c9b07a\" /><path d=\"M508 135 Q528 95 512 80 Q492 100 484 128Z\" fill=\"#efdfb5\" stroke=\"#c9b07a\" /><ellipse cx=\"368\" cy=\"172\" rx=\"36\" ry=\"21\" fill=\"#6f5d55\" transform=\"rotate(-20 368 172)\"/><ellipse cx=\"370\" cy=\"173\" rx=\"20\" ry=\"10\" fill=\"#f6b4b0\" transform=\"rotate(-20 370 173)\"/><ellipse cx=\"552\" cy=\"172\" rx=\"36\" ry=\"21\" fill=\"#6f5d55\" transform=\"rotate(20 552 172)\"/><ellipse cx=\"550\" cy=\"173\" rx=\"20\" ry=\"10\" fill=\"#f6b4b0\" transform=\"rotate(20 550 173)\"/><ellipse cx=\"460\" cy=\"200\" rx=\"95\" ry=\"88\" fill=\"#fbf3e6\" stroke=\"#cdb892\" /><g clip-path=\"url(#cow-ch)\"><path d=\"M480 110 Q560 110 560 190 Q540 235 495 215 Q460 170 480 110Z\" fill=\"#6f5d55\" /></g><ellipse cx=\"460\" cy=\"255\" rx=\"72\" ry=\"44\" fill=\"#f8c3bb\" stroke=\"#dc9590\" /><ellipse cx=\"438\" cy=\"250\" rx=\"7\" ry=\"11\" fill=\"#c47f7c\" /><ellipse cx=\"482\" cy=\"250\" rx=\"7\" ry=\"11\" fill=\"#c47f7c\" /><path d=\"M446 272 Q460 286 474 272\" fill=\"none\" stroke=\"#8a5048\" stroke-width=\"5\"/><ellipse cx=\"385\" cy=\"232\" rx=\"18\" ry=\"12.6\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"535\" cy=\"232\" rx=\"18\" ry=\"12.6\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 394.0,
      "y": 160.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -0.0
     },
     {
      "x": 470.0,
      "y": 160.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -0.0
     }
    ]
   }
  ]
 },
 "horse": {
  "defs": "<filter id=\"horse-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"horse-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"285\" cy=\"470\" rx=\"200\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#horse-s)\" style=\"transform-origin:285px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     115.0,
     260.0
    ],
    "svg": "<g filter=\"url(#horse-w)\"><path d=\"M112 250 Q35 270 52 400 Q70 430 98 400 Q88 320 130 285Z\" fill=\"#7a4a2b\" stroke=\"#5e3820\" /></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#horse-w)\"><rect x=\"165\" y=\"345\" width=\"42\" height=\"122\" rx=\"21\" fill=\"#c08a58\" stroke=\"#a8713f\" /><rect x=\"163\" y=\"443\" width=\"46\" height=\"24\" rx=\"10\" fill=\"#5b3d28\" /><rect x=\"340\" y=\"345\" width=\"42\" height=\"122\" rx=\"21\" fill=\"#c08a58\" stroke=\"#a8713f\" /><rect x=\"338\" y=\"443\" width=\"46\" height=\"24\" rx=\"10\" fill=\"#5b3d28\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#horse-w)\"><ellipse cx=\"398\" cy=\"190\" rx=\"26\" ry=\"26\" fill=\"#7a4a2b\" /><ellipse cx=\"380\" cy=\"225\" rx=\"27\" ry=\"27\" fill=\"#7a4a2b\" /><ellipse cx=\"368\" cy=\"262\" rx=\"27\" ry=\"27\" fill=\"#7a4a2b\" /><ellipse cx=\"425\" cy=\"265\" rx=\"52\" ry=\"100\" fill=\"#d6a06c\" stroke=\"#a8713f\" transform=\"rotate(24 425 265)\"/><ellipse cx=\"265\" cy=\"295\" rx=\"172\" ry=\"95\" fill=\"#d6a06c\" stroke=\"#a8713f\" /><ellipse cx=\"400\" cy=\"290\" rx=\"40\" ry=\"50\" fill=\"#d6a06c\" /><ellipse cx=\"215\" cy=\"255\" rx=\"70\" ry=\"30\" fill=\"#e6b98a\" opacity=\".55\"/></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#horse-w)\"><rect x=\"120\" y=\"355\" width=\"44\" height=\"112\" rx=\"22\" fill=\"#d6a06c\" stroke=\"#a8713f\" /><rect x=\"118\" y=\"443\" width=\"48\" height=\"24\" rx=\"10\" fill=\"#5b3d28\" /><rect x=\"380\" y=\"355\" width=\"44\" height=\"112\" rx=\"22\" fill=\"#d6a06c\" stroke=\"#a8713f\" /><rect x=\"378\" y=\"443\" width=\"48\" height=\"24\" rx=\"10\" fill=\"#5b3d28\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     420.0,
     320.0
    ],
    "svg": "<g filter=\"url(#horse-w)\"><path d=\"M408 150 Q395 70 440 105Z\" fill=\"#d6a06c\" stroke=\"#a8713f\" /><path d=\"M522 150 Q535 70 490 105Z\" fill=\"#d6a06c\" stroke=\"#a8713f\" /><ellipse cx=\"465\" cy=\"190\" rx=\"76\" ry=\"90\" fill=\"#d6a06c\" stroke=\"#a8713f\" /><ellipse cx=\"465\" cy=\"165\" rx=\"13\" ry=\"36\" fill=\"#fff3e0\" /><path d=\"M440 112 Q465 80 492 112 Q485 150 465 138 Q448 150 440 112Z\" fill=\"#7a4a2b\" /><ellipse cx=\"465\" cy=\"252\" rx=\"60\" ry=\"42\" fill=\"#f0d3b2\" stroke=\"#c99a6c\" /><ellipse cx=\"445\" cy=\"246\" rx=\"7\" ry=\"10\" fill=\"#a8713f\" /><ellipse cx=\"485\" cy=\"246\" rx=\"7\" ry=\"10\" fill=\"#a8713f\" /><path d=\"M451 268 Q465 282 479 268\" fill=\"none\" stroke=\"#8a5048\" stroke-width=\"5\"/><ellipse cx=\"395\" cy=\"225\" rx=\"17\" ry=\"11.899999999999999\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"535\" cy=\"225\" rx=\"17\" ry=\"11.899999999999999\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 398.0,
      "y": 152.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -2.1
     },
     {
      "x": 476.0,
      "y": 152.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -2.1
     }
    ]
   }
  ]
 },
 "donkey": {
  "defs": "<filter id=\"donkey-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"donkey-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"285\" cy=\"470\" rx=\"200\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#donkey-s)\" style=\"transform-origin:285px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     108.0,
     265.0
    ],
    "svg": "<g filter=\"url(#donkey-w)\"><path d=\"M108 265 Q62 300 80 380\" fill=\"none\" stroke=\"#867d81\" style=\"stroke-width:9\"/><ellipse cx=\"80\" cy=\"395\" rx=\"15\" ry=\"24\" fill=\"#5e5658\" /></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#donkey-w)\"><rect x=\"165\" y=\"345\" width=\"40\" height=\"122\" rx=\"20\" fill=\"#a39b9e\" stroke=\"#867d81\" /><rect x=\"163\" y=\"443\" width=\"44\" height=\"24\" rx=\"10\" fill=\"#4e4648\" /><rect x=\"340\" y=\"345\" width=\"40\" height=\"122\" rx=\"20\" fill=\"#a39b9e\" stroke=\"#867d81\" /><rect x=\"338\" y=\"443\" width=\"44\" height=\"24\" rx=\"10\" fill=\"#4e4648\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#donkey-w)\"><ellipse cx=\"400\" cy=\"186\" rx=\"17\" ry=\"20\" fill=\"#5e5658\" /><ellipse cx=\"384\" cy=\"218\" rx=\"17\" ry=\"20\" fill=\"#5e5658\" /><ellipse cx=\"372\" cy=\"250\" rx=\"17\" ry=\"20\" fill=\"#5e5658\" /><ellipse cx=\"425\" cy=\"265\" rx=\"50\" ry=\"100\" fill=\"#b9b1b4\" stroke=\"#867d81\" transform=\"rotate(24 425 265)\"/><ellipse cx=\"265\" cy=\"300\" rx=\"166\" ry=\"92\" fill=\"#b9b1b4\" stroke=\"#867d81\" /><ellipse cx=\"400\" cy=\"292\" rx=\"40\" ry=\"50\" fill=\"#b9b1b4\" /><ellipse cx=\"275\" cy=\"362\" rx=\"100\" ry=\"28\" fill=\"#f3ecea\" opacity=\".85\"/></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#donkey-w)\"><rect x=\"122\" y=\"355\" width=\"42\" height=\"112\" rx=\"21\" fill=\"#b9b1b4\" stroke=\"#867d81\" /><rect x=\"120\" y=\"443\" width=\"46\" height=\"24\" rx=\"10\" fill=\"#4e4648\" /><rect x=\"378\" y=\"355\" width=\"42\" height=\"112\" rx=\"21\" fill=\"#b9b1b4\" stroke=\"#867d81\" /><rect x=\"376\" y=\"443\" width=\"46\" height=\"24\" rx=\"10\" fill=\"#4e4648\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     420.0,
     320.0
    ],
    "svg": "<g filter=\"url(#donkey-w)\"><ellipse cx=\"410\" cy=\"98\" rx=\"24\" ry=\"68\" fill=\"#b9b1b4\" stroke=\"#867d81\" transform=\"rotate(-14 410 98)\"/><ellipse cx=\"410\" cy=\"102\" rx=\"11\" ry=\"46\" fill=\"#f7b0b8\" transform=\"rotate(-14 410 102)\"/><ellipse cx=\"520\" cy=\"98\" rx=\"24\" ry=\"68\" fill=\"#b9b1b4\" stroke=\"#867d81\" transform=\"rotate(14 520 98)\"/><ellipse cx=\"520\" cy=\"102\" rx=\"11\" ry=\"46\" fill=\"#f7b0b8\" transform=\"rotate(14 520 102)\"/><ellipse cx=\"465\" cy=\"200\" rx=\"76\" ry=\"90\" fill=\"#b9b1b4\" stroke=\"#867d81\" /><path d=\"M446 118 l8 -22 l10 18 l10 -20 l10 24 Q466 140 446 118Z\" fill=\"#5e5658\" /><ellipse cx=\"465\" cy=\"260\" rx=\"64\" ry=\"46\" fill=\"#fbf5ef\" stroke=\"#cfc5bd\" /><ellipse cx=\"444\" cy=\"254\" rx=\"7\" ry=\"10\" fill=\"#8a7f80\" /><ellipse cx=\"486\" cy=\"254\" rx=\"7\" ry=\"10\" fill=\"#8a7f80\" /><path d=\"M450 276 Q465 291 480 276\" fill=\"none\" stroke=\"#8a5048\" stroke-width=\"5\"/><ellipse cx=\"392\" cy=\"232\" rx=\"17\" ry=\"11.899999999999999\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"538\" cy=\"232\" rx=\"17\" ry=\"11.899999999999999\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 398.0,
      "y": 160.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -7.0
     },
     {
      "x": 476.0,
      "y": 160.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -7.0
     }
    ]
   }
  ]
 },
 "pig": {
  "defs": "<filter id=\"pig-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"pig-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"285\" cy=\"470\" rx=\"200\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#pig-s)\" style=\"transform-origin:285px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     110.0,
     292.0
    ],
    "svg": "<g filter=\"url(#pig-w)\"><path d=\"M110 292 c-32 -4 -42 -42 -16 -46 c20 -3 23 22 5 23 c-20 0 -24 -28 -42 -32\" fill=\"none\" stroke=\"#e0919f\" style=\"stroke-width:9\"/></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#pig-w)\"><rect x=\"170\" y=\"375\" width=\"48\" height=\"90\" rx=\"24\" fill=\"#eaa9b1\" stroke=\"#e0919f\" /><rect x=\"168\" y=\"445\" width=\"52\" height=\"20\" rx=\"10\" fill=\"#d67689\" /><rect x=\"335\" y=\"375\" width=\"48\" height=\"90\" rx=\"24\" fill=\"#eaa9b1\" stroke=\"#e0919f\" /><rect x=\"333\" y=\"445\" width=\"52\" height=\"20\" rx=\"10\" fill=\"#d67689\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#pig-w)\"><ellipse cx=\"270\" cy=\"315\" rx=\"172\" ry=\"112\" fill=\"#f8c2c4\" stroke=\"#e0919f\" /><ellipse cx=\"215\" cy=\"270\" rx=\"60\" ry=\"35\" fill=\"#fcd6d6\" opacity=\".6\"/></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#pig-w)\"><rect x=\"125\" y=\"385\" width=\"50\" height=\"82\" rx=\"25\" fill=\"#f8c2c4\" stroke=\"#e0919f\" /><rect x=\"123\" y=\"447\" width=\"54\" height=\"20\" rx=\"10\" fill=\"#d67689\" /><rect x=\"375\" y=\"385\" width=\"50\" height=\"82\" rx=\"25\" fill=\"#f8c2c4\" stroke=\"#e0919f\" /><rect x=\"373\" y=\"447\" width=\"54\" height=\"20\" rx=\"10\" fill=\"#d67689\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     430.0,
     300.0
    ],
    "svg": "<g filter=\"url(#pig-w)\"><path d=\"M372 190 Q350 100 425 138Z\" fill=\"#ee97a8\" stroke=\"#e0919f\" /><path d=\"M538 190 Q560 100 485 138Z\" fill=\"#ee97a8\" stroke=\"#e0919f\" /><ellipse cx=\"455\" cy=\"228\" rx=\"98\" ry=\"92\" fill=\"#f8c2c4\" stroke=\"#e0919f\" /><ellipse cx=\"455\" cy=\"268\" rx=\"50\" ry=\"35\" fill=\"#ee97a8\" stroke=\"#d67689\" /><ellipse cx=\"438\" cy=\"268\" rx=\"8\" ry=\"12\" fill=\"#c2607a\" /><ellipse cx=\"472\" cy=\"268\" rx=\"8\" ry=\"12\" fill=\"#c2607a\" /><path d=\"M442 310 Q455 323 468 310\" fill=\"none\" stroke=\"#c2607a\" stroke-width=\"5\"/><ellipse cx=\"380\" cy=\"262\" rx=\"18\" ry=\"12.6\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"530\" cy=\"262\" rx=\"18\" ry=\"12.6\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 387.0,
      "y": 180.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -0.7
     },
     {
      "x": 467.0,
      "y": 180.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -0.7
     }
    ]
   }
  ]
 },
 "sheep": {
  "defs": "<filter id=\"sheep-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"sheep-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"285\" cy=\"470\" rx=\"200\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#sheep-s)\" style=\"transform-origin:285px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     125.0,
     290.0
    ],
    "svg": "<g filter=\"url(#sheep-w)\"><ellipse cx=\"100\" cy=\"290\" rx=\"30\" ry=\"28\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#sheep-w)\"><rect x=\"185\" y=\"370\" width=\"30\" height=\"95\" rx=\"15\" fill=\"#5d534e\" /><rect x=\"183\" y=\"447\" width=\"34\" height=\"18\" rx=\"10\" fill=\"#3f3835\" /><rect x=\"335\" y=\"370\" width=\"30\" height=\"95\" rx=\"15\" fill=\"#5d534e\" /><rect x=\"333\" y=\"447\" width=\"34\" height=\"18\" rx=\"10\" fill=\"#3f3835\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#sheep-w)\"><ellipse cx=\"420\" cy=\"295\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"396\" cy=\"341\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"332\" cy=\"372\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"249\" cy=\"379\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"172\" cy=\"359\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"126\" cy=\"319\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"126\" cy=\"271\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"172\" cy=\"231\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"249\" cy=\"211\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"332\" cy=\"218\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"396\" cy=\"249\" rx=\"46\" ry=\"46\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"270\" cy=\"295\" rx=\"150\" ry=\"88\" fill=\"#fffaf0\" /><path d=\"M210 270 q20 -20 40 0 M290 320 q20 -20 40 0 M200 340 q15 -15 30 0\" fill=\"none\" stroke=\"#d6c8b0\" /></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#sheep-w)\"><rect x=\"145\" y=\"375\" width=\"32\" height=\"90\" rx=\"16\" fill=\"#6e625c\" /><rect x=\"143\" y=\"447\" width=\"36\" height=\"18\" rx=\"10\" fill=\"#3f3835\" /><rect x=\"375\" y=\"375\" width=\"32\" height=\"90\" rx=\"16\" fill=\"#6e625c\" /><rect x=\"373\" y=\"447\" width=\"36\" height=\"18\" rx=\"10\" fill=\"#3f3835\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     440.0,
     300.0
    ],
    "svg": "<g filter=\"url(#sheep-w)\"><ellipse cx=\"374\" cy=\"222\" rx=\"36\" ry=\"17\" fill=\"#6e625c\" transform=\"rotate(25 374 222)\"/><ellipse cx=\"546\" cy=\"222\" rx=\"36\" ry=\"17\" fill=\"#6e625c\" transform=\"rotate(-25 546 222)\"/><ellipse cx=\"460\" cy=\"228\" rx=\"74\" ry=\"80\" fill=\"#6e625c\" stroke=\"#574c47\" /><ellipse cx=\"428\" cy=\"158\" rx=\"30\" ry=\"30\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"492\" cy=\"158\" rx=\"30\" ry=\"30\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"460\" cy=\"146\" rx=\"34\" ry=\"34\" fill=\"#fffaf0\" stroke=\"#d6c8b0\" /><ellipse cx=\"460\" cy=\"165\" rx=\"40\" ry=\"22\" fill=\"#fffaf0\" /><ellipse cx=\"460\" cy=\"268\" rx=\"12\" ry=\"8\" fill=\"#f3a9a8\" /><path d=\"M460 276 v8 M446 290 Q460 300 474 290\" fill=\"none\" stroke=\"#f3d9cf\" style=\"stroke-width:4\"/><ellipse cx=\"405\" cy=\"262\" rx=\"15\" ry=\"10.5\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"515\" cy=\"262\" rx=\"15\" ry=\"10.5\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 404.0,
      "y": 199.0,
      "w": 52.0,
      "h": 52.0,
      "delay": -1.4
     },
     {
      "x": 464.0,
      "y": 199.0,
      "w": 52.0,
      "h": 52.0,
      "delay": -1.4
     }
    ]
   }
  ]
 },
 "goat": {
  "defs": "<filter id=\"goat-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"goat-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"285\" cy=\"470\" rx=\"175\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#goat-s)\" style=\"transform-origin:285px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     135.0,
     285.0
    ],
    "svg": "<g filter=\"url(#goat-w)\"><ellipse cx=\"118\" cy=\"258\" rx=\"14\" ry=\"32\" fill=\"#f6f0e6\" stroke=\"#c9bda8\" transform=\"rotate(-35 118 258)\"/></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#goat-w)\"><rect x=\"180\" y=\"360\" width=\"36\" height=\"105\" rx=\"18\" fill=\"#e2d9c8\" stroke=\"#c9bda8\" /><rect x=\"178\" y=\"445\" width=\"40\" height=\"20\" rx=\"10\" fill=\"#6b5d52\" /><rect x=\"335\" y=\"360\" width=\"36\" height=\"105\" rx=\"18\" fill=\"#e2d9c8\" stroke=\"#c9bda8\" /><rect x=\"333\" y=\"445\" width=\"40\" height=\"20\" rx=\"10\" fill=\"#6b5d52\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#goat-w)\"><ellipse cx=\"270\" cy=\"310\" rx=\"152\" ry=\"88\" fill=\"#f6f0e6\" stroke=\"#c9bda8\" /><ellipse cx=\"205\" cy=\"290\" rx=\"52\" ry=\"40\" fill=\"#d9c3a0\" opacity=\".8\"/><ellipse cx=\"320\" cy=\"340\" rx=\"36\" ry=\"26\" fill=\"#d9c3a0\" opacity=\".8\"/></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#goat-w)\"><rect x=\"135\" y=\"368\" width=\"38\" height=\"98\" rx=\"19\" fill=\"#f6f0e6\" stroke=\"#c9bda8\" /><rect x=\"133\" y=\"446\" width=\"42\" height=\"20\" rx=\"10\" fill=\"#6b5d52\" /><rect x=\"375\" y=\"368\" width=\"38\" height=\"98\" rx=\"19\" fill=\"#f6f0e6\" stroke=\"#c9bda8\" /><rect x=\"373\" y=\"446\" width=\"42\" height=\"20\" rx=\"10\" fill=\"#6b5d52\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     430.0,
     300.0
    ],
    "svg": "<g filter=\"url(#goat-w)\"><path d=\"M428 145 Q410 70 368 72 Q396 96 400 152Z\" fill=\"#b9a98c\" stroke=\"#8f8068\" /><path d=\"M482 145 Q500 70 542 72 Q514 96 510 152Z\" fill=\"#b9a98c\" stroke=\"#8f8068\" /><ellipse cx=\"366\" cy=\"200\" rx=\"38\" ry=\"16\" fill=\"#f6f0e6\" stroke=\"#c9bda8\" transform=\"rotate(-18 366 200)\"/><ellipse cx=\"368\" cy=\"200\" rx=\"22\" ry=\"8\" fill=\"#f7b0b8\" transform=\"rotate(-18 368 200)\"/><ellipse cx=\"544\" cy=\"200\" rx=\"38\" ry=\"16\" fill=\"#f6f0e6\" stroke=\"#c9bda8\" transform=\"rotate(18 544 200)\"/><ellipse cx=\"542\" cy=\"200\" rx=\"22\" ry=\"8\" fill=\"#f7b0b8\" transform=\"rotate(18 542 200)\"/><path d=\"M436 290 Q455 352 474 290Z\" fill=\"#e6dccb\" stroke=\"#c9bda8\" /><ellipse cx=\"455\" cy=\"218\" rx=\"80\" ry=\"84\" fill=\"#f6f0e6\" stroke=\"#c9bda8\" /><ellipse cx=\"455\" cy=\"266\" rx=\"48\" ry=\"34\" fill=\"#fbe3d6\" stroke=\"#dcb9a6\" /><path d=\"M446 254 h18 l-9 10Z\" fill=\"#e58a90\" /><path d=\"M443 274 Q455 286 467 274\" fill=\"none\" stroke=\"#8a5048\" stroke-width=\"5\"/><ellipse cx=\"392\" cy=\"250\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"518\" cy=\"250\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 392.0,
      "y": 178.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -5.6
     },
     {
      "x": 462.0,
      "y": 178.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -5.6
     }
    ]
   }
  ]
 },
 "dog": {
  "defs": "<filter id=\"dog-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"dog-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"285\" cy=\"470\" rx=\"175\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#dog-s)\" style=\"transform-origin:285px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     130.0,
     300.0
    ],
    "svg": "<g filter=\"url(#dog-w)\"><path d=\"M130 300 Q82 275 90 200\" fill=\"none\" stroke=\"#ecbd80\" style=\"stroke-width:26\"/><ellipse cx=\"90\" cy=\"196\" rx=\"14\" ry=\"16\" fill=\"#fff6e6\" /></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#dog-w)\"><rect x=\"180\" y=\"370\" width=\"42\" height=\"95\" rx=\"21\" fill=\"#d9a868\" stroke=\"#b98845\" /><rect x=\"178\" y=\"445\" width=\"46\" height=\"20\" rx=\"10\" fill=\"#f1e2c8\" /><rect x=\"335\" y=\"370\" width=\"42\" height=\"95\" rx=\"21\" fill=\"#d9a868\" stroke=\"#b98845\" /><rect x=\"333\" y=\"445\" width=\"46\" height=\"20\" rx=\"10\" fill=\"#f1e2c8\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#dog-w)\"><ellipse cx=\"270\" cy=\"320\" rx=\"152\" ry=\"86\" fill=\"#ecbd80\" stroke=\"#b98845\" /><ellipse cx=\"290\" cy=\"365\" rx=\"80\" ry=\"32\" fill=\"#fff6e6\" opacity=\".8\"/><ellipse cx=\"200\" cy=\"285\" rx=\"46\" ry=\"34\" fill=\"#8a5a36\" opacity=\".85\"/></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#dog-w)\"><rect x=\"135\" y=\"378\" width=\"44\" height=\"88\" rx=\"22\" fill=\"#ecbd80\" stroke=\"#b98845\" /><rect x=\"133\" y=\"446\" width=\"48\" height=\"20\" rx=\"10\" fill=\"#fff6e6\" /><rect x=\"375\" y=\"378\" width=\"44\" height=\"88\" rx=\"22\" fill=\"#ecbd80\" stroke=\"#b98845\" /><rect x=\"373\" y=\"446\" width=\"48\" height=\"20\" rx=\"10\" fill=\"#fff6e6\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     430.0,
     300.0
    ],
    "svg": "<g filter=\"url(#dog-w)\"><ellipse cx=\"450\" cy=\"225\" rx=\"94\" ry=\"86\" fill=\"#ecbd80\" stroke=\"#b98845\" /><ellipse cx=\"496\" cy=\"205\" rx=\"40\" ry=\"42\" fill=\"#8a5a36\" opacity=\".85\"/><ellipse cx=\"450\" cy=\"268\" rx=\"54\" ry=\"38\" fill=\"#fff6e6\" stroke=\"#d9c6a0\" /><ellipse cx=\"450\" cy=\"298\" rx=\"12\" ry=\"15\" fill=\"#f58fa0\" stroke=\"#d96a80\" /><path d=\"M432 276 Q450 290 468 276 M450 258 V278\" fill=\"none\" stroke=\"#5a4036\" /><ellipse cx=\"450\" cy=\"250\" rx=\"17\" ry=\"12\" fill=\"#3a2c28\" /><ellipse cx=\"366\" cy=\"232\" rx=\"28\" ry=\"62\" fill=\"#8a5a36\" stroke=\"#6b4326\" transform=\"rotate(14 366 232)\"/><ellipse cx=\"534\" cy=\"232\" rx=\"28\" ry=\"62\" fill=\"#8a5a36\" stroke=\"#6b4326\" transform=\"rotate(-14 534 232)\"/><ellipse cx=\"388\" cy=\"258\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"512\" cy=\"258\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 386.0,
      "y": 177.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -4.2
     },
     {
      "x": 466.0,
      "y": 177.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -4.2
     }
    ]
   }
  ]
 },
 "cat": {
  "defs": "<filter id=\"cat-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"cat-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"285\" cy=\"470\" rx=\"165\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#cat-s)\" style=\"transform-origin:285px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     145.0,
     325.0
    ],
    "svg": "<g filter=\"url(#cat-w)\"><path d=\"M145 325 Q70 310 84 215 Q90 180 114 170\" fill=\"none\" stroke=\"#f6ae62\" style=\"stroke-width:24\"/><path d=\"M82 240 h26 M86 205 h26\" fill=\"none\" stroke=\"#dc8a3a\" style=\"stroke-width:8\"/></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#cat-w)\"><rect x=\"185\" y=\"375\" width=\"36\" height=\"90\" rx=\"18\" fill=\"#e39a50\" stroke=\"#cf7f34\" /><rect x=\"183\" y=\"447\" width=\"40\" height=\"18\" rx=\"10\" fill=\"#fff6e6\" /><rect x=\"330\" y=\"375\" width=\"36\" height=\"90\" rx=\"18\" fill=\"#e39a50\" stroke=\"#cf7f34\" /><rect x=\"328\" y=\"447\" width=\"40\" height=\"18\" rx=\"10\" fill=\"#fff6e6\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#cat-w)\"><ellipse cx=\"272\" cy=\"330\" rx=\"142\" ry=\"76\" fill=\"#f6ae62\" stroke=\"#cf7f34\" /><path d=\"M225 262 q9 24 0 46 M268 256 q9 26 0 50 M311 260 q9 24 0 46\" fill=\"none\" stroke=\"#dc8a3a\" style=\"stroke-width:9\"/><ellipse cx=\"285\" cy=\"372\" rx=\"70\" ry=\"26\" fill=\"#fff6e6\" opacity=\".8\"/></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#cat-w)\"><rect x=\"145\" y=\"382\" width=\"38\" height=\"84\" rx=\"19\" fill=\"#f6ae62\" stroke=\"#cf7f34\" /><rect x=\"143\" y=\"448\" width=\"42\" height=\"18\" rx=\"10\" fill=\"#fff6e6\" /><rect x=\"368\" y=\"382\" width=\"38\" height=\"84\" rx=\"19\" fill=\"#f6ae62\" stroke=\"#cf7f34\" /><rect x=\"366\" y=\"448\" width=\"42\" height=\"18\" rx=\"10\" fill=\"#fff6e6\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     430.0,
     300.0
    ],
    "svg": "<g filter=\"url(#cat-w)\"><path d=\"M366 205 L368 118 L436 168Z\" fill=\"#f6ae62\" stroke=\"#cf7f34\" /><path d=\"M524 205 L522 118 L454 168Z\" fill=\"#f6ae62\" stroke=\"#cf7f34\" /><path d=\"M382 180 L383 142 L414 166Z\" fill=\"#f7b0b8\" /><path d=\"M508 180 L507 142 L476 166Z\" fill=\"#f7b0b8\" /><ellipse cx=\"445\" cy=\"235\" rx=\"94\" ry=\"80\" fill=\"#f6ae62\" stroke=\"#cf7f34\" /><path d=\"M425 160 v24 M445 156 v28 M465 160 v24\" fill=\"none\" stroke=\"#dc8a3a\" style=\"stroke-width:8\"/><ellipse cx=\"428\" cy=\"272\" rx=\"22\" ry=\"16\" fill=\"#fff6e6\" /><ellipse cx=\"462\" cy=\"272\" rx=\"22\" ry=\"16\" fill=\"#fff6e6\" /><path d=\"M436 254 h18 l-9 11Z\" fill=\"#f58fa0\" stroke=\"#d96a80\" /><path d=\"M396 264 l-50 -10 M396 276 l-50 8 M494 264 l50 -10 M494 276 l50 8\" fill=\"none\" stroke=\"#a86a35\" style=\"stroke-width:3\"/><ellipse cx=\"385\" cy=\"262\" rx=\"15\" ry=\"10.5\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"505\" cy=\"262\" rx=\"15\" ry=\"10.5\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 380.0,
      "y": 197.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -4.9
     },
     {
      "x": 454.0,
      "y": 197.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -4.9
     }
    ]
   }
  ]
 },
 "rabbit": {
  "defs": "<filter id=\"rabbit-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"rabbit-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"275\" cy=\"470\" rx=\"160\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#rabbit-s)\" style=\"transform-origin:275px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     160.0,
     350.0
    ],
    "svg": "<g filter=\"url(#rabbit-w)\"><ellipse cx=\"138\" cy=\"350\" rx=\"32\" ry=\"30\" fill=\"#fffaf3\" stroke=\"#d9ccd0\" /></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#rabbit-w)\"><rect x=\"335\" y=\"395\" width=\"34\" height=\"72\" rx=\"17\" fill=\"#c4b6c0\" stroke=\"#a898a6\" /><ellipse cx=\"175\" cy=\"458\" rx=\"48\" ry=\"14\" fill=\"#c4b6c0\" stroke=\"#a898a6\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#rabbit-w)\"><ellipse cx=\"265\" cy=\"345\" rx=\"132\" ry=\"96\" fill=\"#d9cdd6\" stroke=\"#a898a6\" /><ellipse cx=\"300\" cy=\"385\" rx=\"70\" ry=\"40\" fill=\"#fffaf3\" opacity=\".8\"/></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#rabbit-w)\"><ellipse cx=\"195\" cy=\"385\" rx=\"72\" ry=\"62\" fill=\"#d9cdd6\" stroke=\"#a898a6\" /><ellipse cx=\"215\" cy=\"456\" rx=\"56\" ry=\"16\" fill=\"#fffaf3\" stroke=\"#a898a6\" /><rect x=\"368\" y=\"398\" width=\"36\" height=\"70\" rx=\"18\" fill=\"#d9cdd6\" stroke=\"#a898a6\" /><rect x=\"366\" y=\"448\" width=\"40\" height=\"20\" rx=\"10\" fill=\"#fffaf3\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     420.0,
     320.0
    ],
    "svg": "<g filter=\"url(#rabbit-w)\"><ellipse cx=\"392\" cy=\"125\" rx=\"27\" ry=\"84\" fill=\"#d9cdd6\" stroke=\"#a898a6\" transform=\"rotate(-9 392 125)\"/><ellipse cx=\"392\" cy=\"130\" rx=\"13\" ry=\"60\" fill=\"#f7b0b8\" transform=\"rotate(-9 392 130)\"/><ellipse cx=\"470\" cy=\"125\" rx=\"27\" ry=\"84\" fill=\"#d9cdd6\" stroke=\"#a898a6\" transform=\"rotate(11 470 125)\"/><ellipse cx=\"470\" cy=\"130\" rx=\"13\" ry=\"60\" fill=\"#f7b0b8\" transform=\"rotate(11 470 130)\"/><ellipse cx=\"430\" cy=\"250\" rx=\"90\" ry=\"80\" fill=\"#d9cdd6\" stroke=\"#a898a6\" /><rect x=\"423\" y=\"296\" width=\"15\" height=\"17\" rx=\"4\" fill=\"#ffffff\" stroke=\"#c9bcc4\" /><ellipse cx=\"414\" cy=\"286\" rx=\"21\" ry=\"16\" fill=\"#fffaf3\" /><ellipse cx=\"446\" cy=\"286\" rx=\"21\" ry=\"16\" fill=\"#fffaf3\" /><path d=\"M421 268 h18 l-9 10Z\" fill=\"#f58fa0\" stroke=\"#d96a80\" /><ellipse cx=\"368\" cy=\"278\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"492\" cy=\"278\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 366.0,
      "y": 210.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -6.3
     },
     {
      "x": 438.0,
      "y": 210.0,
      "w": 56.0,
      "h": 56.0,
      "delay": -6.3
     }
    ]
   }
  ]
 },
 "chicken": {
  "defs": "<filter id=\"chicken-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"chicken-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"290\" cy=\"470\" rx=\"150\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#chicken-s)\" style=\"transform-origin:290px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     185.0,
     290.0
    ],
    "svg": "<g filter=\"url(#chicken-w)\"><ellipse cx=\"150\" cy=\"235\" rx=\"28\" ry=\"60\" fill=\"#fff8ea\" stroke=\"#d8c6a2\" transform=\"rotate(-35 150 235)\"/><ellipse cx=\"132\" cy=\"270\" rx=\"26\" ry=\"56\" fill=\"#fff8ea\" stroke=\"#d8c6a2\" transform=\"rotate(-60 132 270)\"/><ellipse cx=\"175\" cy=\"215\" rx=\"24\" ry=\"52\" fill=\"#fff8ea\" stroke=\"#d8c6a2\" transform=\"rotate(-15 175 215)\"/></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#chicken-w)\"><path d=\"M255 400 V455 M233 462 L255 452 L279 462 M255 452 V468\" fill=\"none\" stroke=\"#e09a2c\" style=\"stroke-width:9\"/></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#chicken-w)\"><ellipse cx=\"385\" cy=\"270\" rx=\"62\" ry=\"80\" fill=\"#fff8ea\" stroke=\"#d8c6a2\" /><ellipse cx=\"280\" cy=\"315\" rx=\"150\" ry=\"112\" fill=\"#fff8ea\" stroke=\"#d8c6a2\" transform=\"rotate(-12 280 315)\"/><ellipse cx=\"385\" cy=\"285\" rx=\"55\" ry=\"60\" fill=\"#fff8ea\" /></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#chicken-w)\"><path d=\"M325 400 V455 M303 462 L325 452 L349 462 M325 452 V468\" fill=\"none\" stroke=\"#f7b538\" style=\"stroke-width:9\"/></g>"
   },
   {
    "kind": "wg",
    "origin": [
     340.0,
     300.0
    ],
    "svg": "<g filter=\"url(#chicken-w)\"><path d=\"M215 290 Q300 250 350 310 Q330 380 250 375 Q195 350 215 290Z\" fill=\"#f3e4c6\" stroke=\"#d8c6a2\" /><path d=\"M250 345 q20 12 40 0 M265 320 q20 12 40 0\" fill=\"none\" stroke=\"#d8c6a2\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     410.0,
     290.0
    ],
    "svg": "<g filter=\"url(#chicken-w)\"><ellipse cx=\"392\" cy=\"118\" rx=\"20\" ry=\"22\" fill=\"#ea6a5e\" stroke=\"#c94c44\" /><ellipse cx=\"424\" cy=\"106\" rx=\"22\" ry=\"24\" fill=\"#ea6a5e\" stroke=\"#c94c44\" /><ellipse cx=\"455\" cy=\"120\" rx=\"19\" ry=\"21\" fill=\"#ea6a5e\" stroke=\"#c94c44\" /><ellipse cx=\"422\" cy=\"195\" rx=\"80\" ry=\"78\" fill=\"#fff8ea\" stroke=\"#d8c6a2\" /><ellipse cx=\"422\" cy=\"262\" rx=\"12\" ry=\"19\" fill=\"#ea6a5e\" stroke=\"#c94c44\" /><path d=\"M396 222 Q422 208 448 222 Q422 262 396 222Z\" fill=\"#f7b538\" stroke=\"#d98e1f\" /><ellipse cx=\"360\" cy=\"225\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"484\" cy=\"225\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 362.0,
      "y": 162.0,
      "w": 52.0,
      "h": 52.0,
      "delay": -2.8
     },
     {
      "x": 430.0,
      "y": 162.0,
      "w": 52.0,
      "h": 52.0,
      "delay": -2.8
     }
    ]
   }
  ]
 },
 "duck": {
  "defs": "<filter id=\"duck-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".035\" numOctaves=\"2\" seed=\"4\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"9\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"9\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"3\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter><filter id=\"duck-s\"><feGaussianBlur stdDeviation=\"7\"/></filter>",
  "layers": [
   {
    "kind": "sh",
    "origin": null,
    "svg": "<ellipse class=\"sh\" cx=\"285\" cy=\"470\" rx=\"160\" ry=\"16\" fill=\"#5a4630\" opacity=\".2\" filter=\"url(#duck-s)\" style=\"transform-origin:285px 470px\"/>"
   },
   {
    "kind": "tl",
    "origin": [
     150.0,
     345.0
    ],
    "svg": "<g filter=\"url(#duck-w)\"><path d=\"M150 345 Q80 250 102 300 Q95 335 120 365Z\" fill=\"#fbdc6c\" stroke=\"#deb03a\" /></g>"
   },
   {
    "kind": "lb",
    "origin": null,
    "svg": "<g filter=\"url(#duck-w)\"><path d=\"M245 405 V450\" fill=\"none\" stroke=\"#e5872c\" style=\"stroke-width:10\"/><path d=\"M239 448 L285 462 Q255 478 223 466Z\" fill=\"#e5872c\" stroke=\"#d97a1f\" /></g>"
   },
   {
    "kind": "bd",
    "origin": null,
    "svg": "<g filter=\"url(#duck-w)\"><ellipse cx=\"395\" cy=\"285\" rx=\"55\" ry=\"70\" fill=\"#fbdc6c\" stroke=\"#deb03a\" /><ellipse cx=\"270\" cy=\"335\" rx=\"155\" ry=\"95\" fill=\"#fbdc6c\" stroke=\"#deb03a\" /><ellipse cx=\"390\" cy=\"300\" rx=\"50\" ry=\"50\" fill=\"#fbdc6c\" /></g>"
   },
   {
    "kind": "la",
    "origin": null,
    "svg": "<g filter=\"url(#duck-w)\"><path d=\"M310 405 V450\" fill=\"none\" stroke=\"#f59a3c\" style=\"stroke-width:10\"/><path d=\"M304 448 L350 462 Q320 478 288 466Z\" fill=\"#f59a3c\" stroke=\"#d97a1f\" /></g>"
   },
   {
    "kind": "wg",
    "origin": [
     335.0,
     320.0
    ],
    "svg": "<g filter=\"url(#duck-w)\"><path d=\"M190 320 Q270 275 340 325 Q320 390 235 385 Q180 365 190 320Z\" fill=\"#f5ca48\" stroke=\"#deb03a\" /><path d=\"M235 360 q20 12 40 0\" fill=\"none\" stroke=\"#deb03a\" /></g>"
   },
   {
    "kind": "hd",
    "origin": [
     410.0,
     300.0
    ],
    "svg": "<g filter=\"url(#duck-w)\"><path d=\"M415 128 q-5 -35 12 -30 q-8 12 0 28 q8 -28 22 -18 q-14 8 -12 22\" fill=\"none\" stroke=\"#deb03a\" style=\"stroke-width:7\"/><ellipse cx=\"422\" cy=\"205\" rx=\"82\" ry=\"80\" fill=\"#fbdc6c\" stroke=\"#deb03a\" /><ellipse cx=\"422\" cy=\"250\" rx=\"50\" ry=\"21\" fill=\"#f59a3c\" stroke=\"#d97a1f\" /><path d=\"M378 252 Q422 266 466 252\" fill=\"none\" stroke=\"#d97a1f\" /><ellipse cx=\"408\" cy=\"240\" rx=\"3\" ry=\"4\" fill=\"#b8601a\" /><ellipse cx=\"436\" cy=\"240\" rx=\"3\" ry=\"4\" fill=\"#b8601a\" /><ellipse cx=\"356\" cy=\"238\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/><ellipse cx=\"488\" cy=\"238\" rx=\"16\" ry=\"11.2\" fill=\"#f58fa0\" opacity=\".45\"/></g>",
    "eyes": [
     {
      "x": 359.0,
      "y": 165.0,
      "w": 54.0,
      "h": 54.0,
      "delay": -3.5
     },
     {
      "x": 431.0,
      "y": 165.0,
      "w": 54.0,
      "h": 54.0,
      "delay": -3.5
     }
    ]
   }
  ]
 }
};
