#!/usr/bin/env python3
"""Extract the static backdrop and the ambient art (sun, cloud, butterflies,
grass, flowers) from the Farm friends deck's farm.html.

Usage: python3 scripts/extract-ambient.py <deck-slides-folder>
Writes public/farm-backdrop.svg and src/ambient-data.ts.
"""
import re, sys, os, json
root = os.path.join(os.path.dirname(__file__), "..")
s = open(os.path.join(sys.argv[1], "farm.html")).read()
svg = re.search(r'(<svg xmlns.*?</svg>)', s, re.S).group(1)
svg = re.sub(r' style="[^"]*"', '', svg, count=1)
open(os.path.join(root, "public", "farm-backdrop.svg"), "w").write(svg)
emb = re.search(r'<x-embed[^>]*>(.*?)</x-embed>', s, re.S).group(1)
defs = re.search(r'<svg width="0" height="0"><defs>(.*?)</defs></svg>', emb, re.S).group(1)
sun = re.search(r'<div class="sun">(.*?)<div class="e"', emb, re.S).group(1)
rays = re.search(r'<svg class="ry"[^>]*>(.*?)</svg>', sun, re.S).group(1)
face = re.search(r'</svg><svg width="400" height="400" viewBox="0 0 400 400">(.*?)</svg>', sun, re.S).group(1)
cloud = re.search(r'<svg width="420" height="180" viewBox="0 0 420 180" style="transform:scale\(1\)">(.*?)</svg>', emb, re.S).group(1)
bfly = re.findall(r'<svg width="70" height="60" viewBox="0 0 70 60">(.*?)</svg>', emb, re.S)
grass = re.search(r'<svg class="g"[^>]*width="120" height="110" viewBox="0 0 120 110">(.*?)</svg>', emb, re.S).group(1)
flowers = re.findall(r'<svg class="g" style="left:(\d+)px;top:(\d+)px;animation-duration:([\d.]+)s" width="100" height="130" viewBox="0 0 100 130">(.*?)</svg>', emb, re.S)
grasses = re.findall(r'<svg class="g" style="left:(\d+)px;top:(\d+)px;animation-duration:([\d.]+)s" width="120"', emb)
def ns(x):
    x = re.sub(r'id="([^"]+)"', r'id="amb-\1"', x)
    return re.sub(r'url\(#([^)]+)\)', r'url(#amb-\1)', x)
out = {"defs": ns(defs), "rays": ns(rays), "face": ns(face), "cloud": ns(cloud), "butterflies": bfly,
       "grass": ns(grass), "grassAt": [[int(a), int(b)] for a, b, c in grasses],
       "flowers": [{"x": int(a), "y": int(b), "svg": ns(d)} for a, b, c, d in flowers]}
ts = "// Generated by scripts/extract-ambient.py from the Farm friends deck. Do not edit by hand.\n"
ts += "export const AMBIENT = " + json.dumps(out, indent=1) + " as const;\n"
open(os.path.join(root, "src", "ambient-data.ts"), "w").write(ts)
print("wrote public/farm-backdrop.svg and src/ambient-data.ts")
