#!/usr/bin/env python3
"""Extract the animal SVG layers from the Farm friends slide deck into src/animals/data.ts.

Usage: python3 scripts/extract-animals.py <deck-slides-folder>
The deck folder holds one <animal>.html per animal (cow.html, horse.html, ...).
Each animal is a stack of 600x500 SVG layers; we keep the raw inner SVG of each
layer, namespace its ids, and record the pivot points the CSS used.
"""
import json, re, sys, os

ANIMALS = ["cow","horse","donkey","pig","sheep","goat","dog","cat","rabbit","chicken","duck"]
src = sys.argv[1]
out = {}

def ns(svg, name):
    svg = re.sub(r'id="([^"]+)"', lambda m: f'id="{name}-{m.group(1)}"', svg)
    svg = re.sub(r'url\(#([^)]+)\)', lambda m: f'url(#{name}-{m.group(1)})', svg)
    return svg

def origin(style):
    m = re.search(r'transform-origin:\s*([\d.]+)px\s+([\d.]+)px', style or "")
    return [float(m.group(1)), float(m.group(2))] if m else None

for name in ANIMALS:
    html = open(os.path.join(src, name + ".html")).read()
    body = re.search(r'<div id="a" class="w">(.*)</div><script>', html, re.S).group(1)
    inner = re.search(r'<div class="l" style="">(.*)</div>$', body, re.S).group(1)
    layers = []
    defs = ""
    # split top-level children: svgs and the head div
    pos = 0
    tokens = re.finditer(r'<svg class="l ?([a-z]*)" viewBox="0 0 600 500"(?: style="([^"]*)")?>(.*?)</svg>|<div class="hd" style="([^"]*)">(.*)</div>$', inner, re.S)
    for t in tokens:
        if t.group(5) is not None:  # head
            hd = t.group(5)
            hsvg = re.search(r'<svg class="l ?" viewBox="0 0 600 500">(.*?)</svg>', hd, re.S).group(1)
            eyes = []
            for e in re.finditer(r'<div class="e" style="([^"]*)"', hd):
                st = e.group(1)
                g = lambda k: float(re.search(k + r':(-?[\d.]+)', st).group(1))
                eyes.append({"x": g("left"), "y": g("top"), "w": g("width"), "h": g("height"), "delay": g("animation-delay")})
            layers.append({"kind": "hd", "origin": origin(t.group(4)), "svg": ns(hsvg, name), "eyes": eyes})
        else:
            kind = t.group(1) or "sh"
            svg = t.group(3)
            if kind == "sh":
                d = re.search(r'<defs>(.*?)</defs>', svg, re.S)
                if d:
                    defs = ns(d.group(1), name)
                    svg = svg.replace(d.group(0), "")
            layers.append({"kind": kind, "origin": origin(t.group(2)), "svg": ns(svg, name)})
    out[name] = {"defs": defs, "layers": layers}
    print(name, [l["kind"] for l in layers], "eyes", len(layers[-1]["eyes"]))

ts = "// Generated by scripts/extract-animals.py from the Farm friends deck. Do not edit by hand.\n"
ts += "export type Eye = { x: number; y: number; w: number; h: number; delay: number };\n"
ts += "export type Layer = { kind: string; origin: [number, number] | null; svg: string; eyes?: Eye[] };\n"
ts += "export type AnimalArt = { defs: string; layers: Layer[] };\n"
ts += "export const ANIMAL_ART: Record<string, AnimalArt> = " + json.dumps(out, indent=1) + ";\n"
open(os.path.join(os.path.dirname(__file__), "..", "src", "animals", "data.ts"), "w").write(ts)
print("wrote src/animals/data.ts")
