// Generated by scripts/extract-ambient.py from the Farm friends deck. Do not edit by hand.
export const AMBIENT = {
 "defs": "<filter id=\"amb-w\" x=\"-6%\" y=\"-6%\" width=\"112%\" height=\"112%\" color-interpolation-filters=\"sRGB\"><feTurbulence type=\"fractalNoise\" baseFrequency=\".03\" numOctaves=\"2\" seed=\"6\" result=\"n\"/><feDisplacementMap in=\"SourceGraphic\" in2=\"n\" scale=\"8\" xChannelSelector=\"R\" yChannelSelector=\"G\" result=\"d\"/><feTurbulence type=\"fractalNoise\" baseFrequency=\".012\" numOctaves=\"3\" seed=\"11\"/><feColorMatrix type=\"matrix\" values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .5 0 0 0 .74\" result=\"m\"/><feComposite in=\"d\" in2=\"m\" operator=\"in\" result=\"p\"/><feMorphology in=\"d\" operator=\"erode\" radius=\"2\" result=\"e\"/><feComposite in=\"d\" in2=\"e\" operator=\"out\"/><feGaussianBlur stdDeviation=\"1.3\" result=\"r\"/><feMerge><feMergeNode in=\"p\"/><feMergeNode in=\"r\"/></feMerge></filter>",
 "rays": "<g filter=\"url(#amb-w)\"><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(0 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(30 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(60 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(90 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(120 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(150 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(180 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(210 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(240 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(270 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(300 200 200)\"/><rect x=\"192\" y=\"18\" width=\"16\" height=\"50\" rx=\"8\" fill=\"#fbc94a\" transform=\"rotate(330 200 200)\"/></g>",
 "face": "<g filter=\"url(#amb-w)\"><circle cx=\"200\" cy=\"200\" r=\"105\" fill=\"#fbd560\" stroke=\"#efb534\" stroke-width=\"5\"/><ellipse cx=\"140\" cy=\"228\" rx=\"20\" ry=\"13\" fill=\"#f58f7a\" opacity=\".55\"/><ellipse cx=\"260\" cy=\"228\" rx=\"20\" ry=\"13\" fill=\"#f58f7a\" opacity=\".55\"/><path d=\"M172 232 Q200 262 228 232\" fill=\"none\" stroke=\"#8a5a2c\" stroke-width=\"7\" stroke-linecap=\"round\"/></g>",
 "cloud": "<g filter=\"url(#amb-w)\"><ellipse cx=\"90\" cy=\"95\" rx=\"60\" ry=\"48\" fill=\"#fffdf8\" stroke=\"#cfe3ee\" /><ellipse cx=\"170\" cy=\"70\" rx=\"75\" ry=\"60\" fill=\"#fffdf8\" stroke=\"#cfe3ee\" /><ellipse cx=\"260\" cy=\"90\" rx=\"65\" ry=\"52\" fill=\"#fffdf8\" stroke=\"#cfe3ee\" /><ellipse cx=\"330\" cy=\"105\" rx=\"45\" ry=\"36\" fill=\"#fffdf8\" stroke=\"#cfe3ee\" /><ellipse cx=\"200\" cy=\"108\" rx=\"150\" ry=\"40\" fill=\"#fffdf8\" /></g>",
 "butterflies": [
  "<g class=\"wl\"><ellipse cx=\"20\" cy=\"20\" rx=\"17\" ry=\"19\" fill=\"#f59ab5\"/><ellipse cx=\"24\" cy=\"44\" rx=\"12\" ry=\"12\" fill=\"#f8c25c\"/></g><g class=\"wr\"><ellipse cx=\"50\" cy=\"20\" rx=\"17\" ry=\"19\" fill=\"#f59ab5\"/><ellipse cx=\"46\" cy=\"44\" rx=\"12\" ry=\"12\" fill=\"#f8c25c\"/></g><rect x=\"32\" y=\"12\" width=\"6\" height=\"40\" rx=\"3\" fill=\"#5b4636\"/>",
  "<g class=\"wl\"><ellipse cx=\"20\" cy=\"20\" rx=\"17\" ry=\"19\" fill=\"#9fc7f0\"/><ellipse cx=\"24\" cy=\"44\" rx=\"12\" ry=\"12\" fill=\"#c9a6ee\"/></g><g class=\"wr\"><ellipse cx=\"50\" cy=\"20\" rx=\"17\" ry=\"19\" fill=\"#9fc7f0\"/><ellipse cx=\"46\" cy=\"44\" rx=\"12\" ry=\"12\" fill=\"#c9a6ee\"/></g><rect x=\"32\" y=\"12\" width=\"6\" height=\"40\" rx=\"3\" fill=\"#5b4636\"/>"
 ],
 "grass": "<g filter=\"url(#amb-w)\" fill=\"none\" stroke-linecap=\"round\" stroke-width=\"9\"><path d=\"M40 108 Q30 60 12 40\" stroke=\"#5f9f4b\"/><path d=\"M58 108 Q58 50 64 18\" stroke=\"#6aad54\"/><path d=\"M76 108 Q88 64 108 46\" stroke=\"#5f9f4b\"/></g>",
 "grassAt": [
  [
   90,
   960
  ],
  [
   520,
   985
  ],
  [
   1010,
   965
  ],
  [
   1330,
   990
  ],
  [
   1760,
   955
  ]
 ],
 "flowers": [
  {
   "x": 300,
   "y": 930,
   "svg": "<g filter=\"url(#amb-w)\"><path d=\"M50 128 Q46 80 50 40\" stroke=\"#5f9f4b\" stroke-width=\"7\" fill=\"none\" stroke-linecap=\"round\"/><ellipse cx=\"66\" cy=\"96\" rx=\"16\" ry=\"7\" fill=\"#6aad54\" transform=\"rotate(-30 66 96)\"/><circle cx=\"67\" cy=\"30\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"55\" cy=\"46\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"36\" cy=\"40\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"36\" cy=\"20\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"55\" cy=\"14\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"50\" cy=\"30\" r=\"10\" fill=\"#fbd560\"/></g>"
  },
  {
   "x": 760,
   "y": 960,
   "svg": "<g filter=\"url(#amb-w)\"><path d=\"M50 128 Q46 80 50 40\" stroke=\"#5f9f4b\" stroke-width=\"7\" fill=\"none\" stroke-linecap=\"round\"/><ellipse cx=\"66\" cy=\"96\" rx=\"16\" ry=\"7\" fill=\"#6aad54\" transform=\"rotate(-30 66 96)\"/><circle cx=\"67\" cy=\"30\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"55\" cy=\"46\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"36\" cy=\"40\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"36\" cy=\"20\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"55\" cy=\"14\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"50\" cy=\"30\" r=\"10\" fill=\"#fbd560\"/></g>"
  },
  {
   "x": 1180,
   "y": 950,
   "svg": "<g filter=\"url(#amb-w)\"><path d=\"M50 128 Q46 80 50 40\" stroke=\"#5f9f4b\" stroke-width=\"7\" fill=\"none\" stroke-linecap=\"round\"/><ellipse cx=\"66\" cy=\"96\" rx=\"16\" ry=\"7\" fill=\"#6aad54\" transform=\"rotate(-30 66 96)\"/><circle cx=\"67\" cy=\"30\" r=\"13\" fill=\"#f7b2d0\"/><circle cx=\"55\" cy=\"46\" r=\"13\" fill=\"#f7b2d0\"/><circle cx=\"36\" cy=\"40\" r=\"13\" fill=\"#f7b2d0\"/><circle cx=\"36\" cy=\"20\" r=\"13\" fill=\"#f7b2d0\"/><circle cx=\"55\" cy=\"14\" r=\"13\" fill=\"#f7b2d0\"/><circle cx=\"50\" cy=\"30\" r=\"10\" fill=\"#fbd560\"/></g>"
  },
  {
   "x": 1560,
   "y": 940,
   "svg": "<g filter=\"url(#amb-w)\"><path d=\"M50 128 Q46 80 50 40\" stroke=\"#5f9f4b\" stroke-width=\"7\" fill=\"none\" stroke-linecap=\"round\"/><ellipse cx=\"66\" cy=\"96\" rx=\"16\" ry=\"7\" fill=\"#6aad54\" transform=\"rotate(-30 66 96)\"/><circle cx=\"67\" cy=\"30\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"55\" cy=\"46\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"36\" cy=\"40\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"36\" cy=\"20\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"55\" cy=\"14\" r=\"13\" fill=\"#fffaf0\"/><circle cx=\"50\" cy=\"30\" r=\"10\" fill=\"#fbd560\"/></g>"
  },
  {
   "x": 1850,
   "y": 965,
   "svg": "<g filter=\"url(#amb-w)\"><path d=\"M50 128 Q46 80 50 40\" stroke=\"#5f9f4b\" stroke-width=\"7\" fill=\"none\" stroke-linecap=\"round\"/><ellipse cx=\"66\" cy=\"96\" rx=\"16\" ry=\"7\" fill=\"#6aad54\" transform=\"rotate(-30 66 96)\"/><circle cx=\"67\" cy=\"30\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"55\" cy=\"46\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"36\" cy=\"40\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"36\" cy=\"20\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"55\" cy=\"14\" r=\"13\" fill=\"#f58fa0\"/><circle cx=\"50\" cy=\"30\" r=\"10\" fill=\"#fbd560\"/></g>"
  }
 ]
} as const;
